// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWjGlHsSvzS1-PsSpWIaUqqjOqum4iLC0',
    appId: '1:114862653354:web:f880d24e04a2ee0ce635d3',
    messagingSenderId: '114862653354',
    projectId: 'tour4you-ef736',
    authDomain: 'tour4you-ef736.firebaseapp.com',
    storageBucket: 'tour4you-ef736.appspot.com',
    measurementId: 'G-ZG09BV4F4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqjwJXSqBlnyV6I1O1xwWkiRKvm_t_Ik',
    appId: '1:114862653354:android:a5aac24593c41a39e635d3',
    messagingSenderId: '114862653354',
    projectId: 'tour4you-ef736',
    storageBucket: 'tour4you-ef736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxioo0oM2d-ll9-HYoza92El6UjnQvAUY',
    appId: '1:114862653354:ios:f341f4bec2431668e635d3',
    messagingSenderId: '114862653354',
    projectId: 'tour4you-ef736',
    storageBucket: 'tour4you-ef736.appspot.com',
    iosClientId: '114862653354-v664f96al6erpvcvp6chu1rum501e5dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tour4you',
  );
}
